[tool.poetry]
name = "musii-kit"
version = "0.1.3"
description = "Collection of tools for computational musicology"
authors = ["Otso Björklund <otso.bjorklund@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/otsob/musii-kit"

[tool.poetry.dependencies]
python = "3.10.*"
numpy = "^1.21.4"
pandas = "^1.3.4"
jupyter = "^1.0.0"
music21 = "^7.1.0"
matplotlib = "^3.5.0"
scipy = "^1.7.3"
torch = "1.12.1"

[tool.poetry.dev-dependencies]
pytest = "^7.1.0"
flake8 = "^4.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
