[tool.poetry]
name = "musii-kit"
version = "0.1.0"
description = ""
authors = ["Otso Björklund <otso.bjorklund@gmail.com>"]

[tool.poetry.dependencies]
python = "3.8"
numpy = "^1.21.4"
pandas = "^1.3.4"
jupyter = "^1.0.0"
music21 = "^7.1.0"
matplotlib = "^3.5.0"
scipy = "^1.7.3"
torch = "^1.10.0"

[tool.poetry.dev-dependencies]
pybuilder = "^0.13.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
