[package]
name = "posemirpy"
version = "0.4.16"
edition = "2021"

[lib]
name = "posemirpy"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.19.0", features = ["extension-module"] }
posemir = { git = "https://github.com/otsob/posemir.git" }
numpy = { version = "0.19.0" }