name: CI
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.2.2
      - name: Install dependencies
        run: poetry install
      - name: Lint
        run: poetry run ruff check --verbose
      - name: Run tests
        run: poetry run pytest --verbose
